package com.regenworlds.service;

import com.regenworlds.discord.DiscordNotifier;
import com.regenworlds.model.VoidWorldType;
import org.bukkit.plugin.java.JavaPlugin;

import java.io.*;
import java.util.Random;
import java.util.concurrent.TimeUnit;

public class RegenScheduler {
    private final JavaPlugin plugin;
    private final VoidWorldManager worldManager;
    private final DiscordNotifier discord;
    private final File timerFile;
    private final long minMs;
    private final long maxMs;

    private long nextRegenAt = -1;
    private int taskId = -1;

    public RegenScheduler(JavaPlugin plugin, VoidWorldManager worldManager, DiscordNotifier discord,
                          double minHours, double maxHours) {
        this.plugin = plugin;
        this.worldManager = worldManager;
        this.discord = discord;
        this.timerFile = new File(plugin.getDataFolder(), "regen_timer.dat");
        this.minMs = (long)(minHours * 3600_000);
        this.maxMs = (long)(maxHours * 3600_000);
    }

    public void start() {
        nextRegenAt = loadTimer();
        if (nextRegenAt < 0 || nextRegenAt < System.currentTimeMillis()) {
            scheduleNext();
        }
        taskId = plugin.getServer().getScheduler().runTaskTimerAsynchronously(plugin, this::tick, 20L * 60, 20L * 60).getTaskId();
    }

    public void stop() {
        if (taskId >= 0) plugin.getServer().getScheduler().cancelTask(taskId);
    }

    public long getNextRegenAt() {
        return nextRegenAt;
    }

    public void forceRegen() {
        plugin.getServer().getScheduler().runTaskAsynchronously(plugin, () -> regenAll(true));
    }

    private void tick() {
        if (System.currentTimeMillis() >= nextRegenAt) {
            regenAll(false);
            scheduleNext();
        }
    }

    private void regenAll(boolean forced) {
        plugin.getServer().getScheduler().runTask(plugin, () -> {
            for (VoidWorldType type : VoidWorldType.values()) {
                worldManager.regenerateVoidWorld(type);
            }
            String msg = forced ? "Void worlds forcefully regenerated by admin." : "Void worlds have been regenerated with new seeds!";
            plugin.getLogger().info("[RegenWorlds] " + msg);
            discord.sendRegenNotification(msg);
        });
    }

    private void scheduleNext() {
        long delay = minMs + (long)((maxMs - minMs) * new Random().nextDouble());
        nextRegenAt = System.currentTimeMillis() + delay;
        saveTimer(nextRegenAt);
        plugin.getLogger().info("[RegenWorlds] Next regen in " + TimeUnit.MILLISECONDS.toHours(delay) + "h");
    }

    private long loadTimer() {
        if (!timerFile.exists()) return -1;
        try (DataInputStream in = new DataInputStream(new FileInputStream(timerFile))) {
            return in.readLong();
        } catch (Exception e) {
            return -1;
        }
    }

    private void saveTimer(long time) {
        timerFile.getParentFile().mkdirs();
        try (DataOutputStream out = new DataOutputStream(new FileOutputStream(timerFile))) {
            out.writeLong(time);
        } catch (Exception ignored) {}
    }
}
